### ISSUE TITLE
YuniKorn節點排序: 如何避免資源使用破碎？

### ISSUE THREAD

**Issue by chia7712** [skiptests/astraea#243]
**背景**
1. 叢集資源不足以一次消化所有任務
2. 不同任務所要求的資源差異慎大
3. 同一個類型的任務再次提交時也可能要求不同的資源量
4. 任務所需的資源量大部分是動態決定

**問題描述**

如何避免叢集出現有些節點的cpu被耗盡，但有一堆閒置memory; 或是有一堆閒置cpu，但memory都被耗盡？這個問題會導致整體叢集的資源使用率不佳

**延伸問題**
1. 節點排序的演算法是綁定在`partition`上面，換言之提交到同一個partition的任務都必須使用同一個演算法？
2. 承上，如果是綁在`partition`上面的話，那麼是否能動態更新節點排序演算法的參數？
3. 承上，如果可以動態更新的話，那麼我們可否設計一個機制來避免資源破碎？

**Comment by chia7712** [comment]
@chungen0126 這是一個我最近收到的題目中比較有趣，也可能蠻適合做論文的題目，在客戶生產環境中，破碎的資源造成很大的硬體浪費，例如一千萬的設備中可能只有五百萬的硬體被使用，因此如果能提出一個方法來避免資源破碎的話，可以給真實生產環境中帶來很大的幫助

你如果有興趣的話可否研究一下？一些細節如果我沒描述清楚也請告知

**Comment by chungen0126** [comment]
目前yunikorn能使用的node policy機制主要有：
1. BinPackingPolicy
2. FairnessPolicy
https://github.com/apache/incubator-yunikorn-core/blob/ff851af3b3586b0df2a3bb9c499a05328f311973/pkg/scheduler/objects/nodesorting.go#L36-L42
根據以上程式碼段看來，目前binPackingNodeSortingPolicy & fairnessNodeSortingPolicy 能使用的參數只有resource weight。

這邊有我之前針對node policy的相關測試
https://github.com/skiptests/astraea/issues/201#issuecomment-1031870749

目前調整node policy的狀態是透過`pc.updateNodeSortingPolicy`此function會在
 `initialPartitionFromConfig` 以及 `updatePartitionDetails`兩種情況下更新。前者主要是剛啟動時，初始化會被執行，而後者會在一些情況下更新，如下。

目前沒有單獨對node policy做動態更新的方法，但可以透過發起`RMConfigUpdateEvent`和`processRMRegistrationEvent`這種event做更新，這兩種更新方法會更新整個scheduler，前者透過configmap更新，後者是在是讀取程式暫存的參數可以在test的時候使用。

**Comment by chia7712** [comment]
> 目前沒有單獨對node policy做動態更新的方法，但可以透過發起RMConfigUpdateEvent和processRMRegistrationEvent這種event做更新，這兩種更新方法會更新整個scheduler，前者透過configmap更新，後者是在是讀取程式暫存的參數可以在test的時候使用。

假如要考慮相容性的話，我們是否有機會用restful APIs動態更新node policy (https://yunikorn.apache.org/docs/api/scheduler#configuration-update)? 

另外你對這個題目有興趣嗎？如果有的話，我們明天禮拜三討論一下細節

**Comment by chungen0126** [comment]
> 假如要考慮相容性的話，我們是否有機會用restful APIs動態更新node policy (https://yunikorn.apache.org/docs/api/scheduler#configuration-update)?

想請問使用restful APIs更新具體的做法是？這個意思是不是本身扮演client去發送request？
> 另外你對這個題目有興趣嗎？如果有的話，我們明天禮拜三討論一下細節

有的。

**Comment by chia7712** [comment]
> 想請問使用restful APIs更新具體的做法是？這個意思是不是本身扮演client去發送request？

如果我沒記錯的話，yunikorn可以動態更新參數，所以一個相容性比較高的做法是如你後面那句，我們另外開一隻程式去監控狀態並且適時的更新node policy的參數，讓其改變排序

上面是我一個很直覺的做法，可能需要再打磨一下

**Comment by chungen0126** [comment]
目前測試下來 restful APIs動態去更新是可行的。
主要可能有幾個設定要注意：

1. `ENABLE_CONFIG_HOT_REFRESH`預設為true，可以透過`kubectl apply -f `的時候去設定。
這裡是yaml檔範例
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yunikorn
  name: yunikorn-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yunikorn
  template:
    metadata:
      labels:
        app: yunikorn
        component: yunikorn-scheduler
      name: yunikorn-scheduler
    spec:
      hostNetwork: true
      serviceAccountName: yunikorn-admin
      containers:
        - name: yunikorn-scheduler-k8s
          image: wfps1210/yunikorn:scheduler-latest
          env:
            - name: ENABLE_CONFIG_HOT_REFRESH
              value: "false"
            - name: LOG_ENCODING
              value: console
            - name: LOG_LEVEL
              value: '-1'
            - name: CLUSTER_ID
              value: myCluster
            - name: CLUSTER_VERSION
              value: latest
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 4
              memory: 2Gi
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/yunikorn/
        - name: yunikorn-scheduler-web
          image: apache/yunikorn:web-latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 500Mi
          ports:
            - containerPort: 9889
      volumes:
        - name: config-volume
          configMap:
            name: yunikorn-configs
```
2. 需要將configmap label 成 app=yunikorn
以下是指令範例
`kubectl label configmap yunikorn-configs app=yunikorn`

**Comment by chia7712** [comment]
> ENABLE_CONFIG_HOT_REFRESH預設為true

這代表預設可以動態更新吧？

> 需要將configmap label 成 app=yunikorn

你上方提供的yaml 不是已經有指定了嗎？

**Comment by chungen0126** [comment]
> 這代表預設可以動態更新吧？

根據目前的yunikorn原始碼，透過`kubectl create configmap`更新和透過restful APIs更新configmap這兩種方式在同一種設定下只有一個能實行。
兩者是透過同一個參數`ENABLE_CONFIG_HOT_REFRESH`來設定。
設定成true使用前者方式更新configmap，根據下面的程式碼段。
https://github.com/apache/incubator-yunikorn-k8shim/blob/a61fc0052c07e510503853db74030290bbda562b/pkg/cache/context.go#L306-L322

而設定成false則使用後者，根據下面程式碼段。
https://github.com/apache/incubator-yunikorn-k8shim/blob/a61fc0052c07e510503853db74030290bbda562b/pkg/cache/context.go#L928-L934
> 你上方提供的yaml 不是已經有指定了嗎？

這邊所說的configmap label 成 app=yunikorn指的是以下這個yaml檔
```
  - name: default
    nodesortpolicy:
        type: fair
        resourceweights:
          vcore: 1.0
          memory: 9.0
    queues:
    - name: root
      submitacl: '*'
      queues:
        - name: stateaware
          submitacl: '*'
          properties:
            application.sort.policy: stateaware
        - name: fifo
          submitacl: '*'
          properties:
            application.sort.policy: fifo
```
